services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env

  db:
    container_name: db
    image: 'postgres:16.3-bullseye'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
