services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env

  db:
    container_name: db
    image: 'mysql:9.0'
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
